'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace srvFileTransferService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srvFileTransferService.IFileTransfer")>  _
    Public Interface IFileTransfer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFileTransfer/SaveFile", ReplyAction:="http://tempuri.org/IFileTransfer/SaveFileResponse")>  _
        Sub SaveFile(ByVal inputFile() As Byte, ByVal ClientName As String, ByVal HospCode As String, ByVal RootDirectory As String, ByVal ClientDirectory As String, ByVal FilePath As String, ByVal overWrite As Boolean, ByVal XMLParams As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFileTransfer/GetFile", ReplyAction:="http://tempuri.org/IFileTransfer/GetFileResponse")>  _
        Function GetFile(ByVal ClientName As String, ByVal HospCode As String, ByVal RootDirectory As String, ByVal ClientDirectory As String, ByVal FilePath As String, ByVal XMLParams As String) As Byte()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IFileTransferChannel
        Inherits srvFileTransferService.IFileTransfer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FileTransferClient
        Inherits System.ServiceModel.ClientBase(Of srvFileTransferService.IFileTransfer)
        Implements srvFileTransferService.IFileTransfer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub SaveFile(ByVal inputFile() As Byte, ByVal ClientName As String, ByVal HospCode As String, ByVal RootDirectory As String, ByVal ClientDirectory As String, ByVal FilePath As String, ByVal overWrite As Boolean, ByVal XMLParams As String) Implements srvFileTransferService.IFileTransfer.SaveFile
            MyBase.Channel.SaveFile(inputFile, ClientName, HospCode, RootDirectory, ClientDirectory, FilePath, overWrite, XMLParams)
        End Sub
        
        Public Function GetFile(ByVal ClientName As String, ByVal HospCode As String, ByVal RootDirectory As String, ByVal ClientDirectory As String, ByVal FilePath As String, ByVal XMLParams As String) As Byte() Implements srvFileTransferService.IFileTransfer.GetFile
            Return MyBase.Channel.GetFile(ClientName, HospCode, RootDirectory, ClientDirectory, FilePath, XMLParams)
        End Function
    End Class
End Namespace
