//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com.dcsglobal.voicerecorder", ConfigurationName="srVoiceRecorder.VoiceRecorderSoap")]
    public interface VoiceRecorderSoap {
        
        // CODEGEN: Generating message contract since element name USER_ID from namespace http://com.dcsglobal.voicerecorder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/AddTrack", ReplyAction="*")]
        DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackResponse AddTrack(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/TrackSent", ReplyAction="*")]
        int TrackSent(int TRACK_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/TrackDetailSent", ReplyAction="*")]
        int TrackDetailSent(int TRACK_DETAIL_ID);
        
        // CODEGEN: Generating message contract since element name TRACK_FILE_NAME from namespace http://com.dcsglobal.voicerecorder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/UpdateTrackDetails", ReplyAction="*")]
        DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackDetailsResponse UpdateTrackDetails(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetHospCodeResult from namespace http://com.dcsglobal.voicerecorder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/GetHospCode", ReplyAction="*")]
        DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.GetHospCodeResponse GetHospCode(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.GetHospCodeRequest request);
        
        // CODEGEN: Generating message contract since element name TRACK_DETAIL_FILE_NAME from namespace http://com.dcsglobal.voicerecorder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/AddTrackDetail", ReplyAction="*")]
        DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackDetailResponse AddTrackDetail(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackDetailRequest request);
        
        // CODEGEN: Generating message contract since element name TRACK_FILE_NAME from namespace http://com.dcsglobal.voicerecorder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/UpdateTrack", ReplyAction="*")]
        DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackResponse UpdateTrack(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrack", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackRequestBody Body;
        
        public AddTrackRequest() {
        }
        
        public AddTrackRequest(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class AddTrackRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string USER_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SOURCE_DEVICE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TRACK_FILE_NAME;
        
        public AddTrackRequestBody() {
        }
        
        public AddTrackRequestBody(string USER_ID, string SOURCE_DEVICE, string TRACK_FILE_NAME) {
            this.USER_ID = USER_ID;
            this.SOURCE_DEVICE = SOURCE_DEVICE;
            this.TRACK_FILE_NAME = TRACK_FILE_NAME;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrackResponse", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackResponseBody Body;
        
        public AddTrackResponse() {
        }
        
        public AddTrackResponse(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class AddTrackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddTrackResult;
        
        public AddTrackResponseBody() {
        }
        
        public AddTrackResponseBody(int AddTrackResult) {
            this.AddTrackResult = AddTrackResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTrackDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTrackDetails", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackDetailsRequestBody Body;
        
        public UpdateTrackDetailsRequest() {
        }
        
        public UpdateTrackDetailsRequest(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class UpdateTrackDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TRACK_DETAIL_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TRACK_FILE_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TRACK_DETAIL_SUBJECT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TRACK_DETAIL_NOTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string USER_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int START_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int END_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string HOSP_CODE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ACCOUNT_NUMBER;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string MRN;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.DateTime DOB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string SOURCE_DEVICE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string CLIENT_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ROOT_DIRECTORY;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CLIENT_DIRECTORY;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string FILE_PATH;
        
        public UpdateTrackDetailsRequestBody() {
        }
        
        public UpdateTrackDetailsRequestBody(
                    int TRACK_DETAIL_ID, 
                    string TRACK_FILE_NAME, 
                    string TRACK_DETAIL_SUBJECT, 
                    string TRACK_DETAIL_NOTE, 
                    string USER_ID, 
                    int START_TIME, 
                    int END_TIME, 
                    string HOSP_CODE, 
                    string ACCOUNT_NUMBER, 
                    string MRN, 
                    System.DateTime DOB, 
                    string SOURCE_DEVICE, 
                    string CLIENT_NAME, 
                    string ROOT_DIRECTORY, 
                    string CLIENT_DIRECTORY, 
                    string FILE_PATH) {
            this.TRACK_DETAIL_ID = TRACK_DETAIL_ID;
            this.TRACK_FILE_NAME = TRACK_FILE_NAME;
            this.TRACK_DETAIL_SUBJECT = TRACK_DETAIL_SUBJECT;
            this.TRACK_DETAIL_NOTE = TRACK_DETAIL_NOTE;
            this.USER_ID = USER_ID;
            this.START_TIME = START_TIME;
            this.END_TIME = END_TIME;
            this.HOSP_CODE = HOSP_CODE;
            this.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            this.MRN = MRN;
            this.DOB = DOB;
            this.SOURCE_DEVICE = SOURCE_DEVICE;
            this.CLIENT_NAME = CLIENT_NAME;
            this.ROOT_DIRECTORY = ROOT_DIRECTORY;
            this.CLIENT_DIRECTORY = CLIENT_DIRECTORY;
            this.FILE_PATH = FILE_PATH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTrackDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTrackDetailsResponse", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackDetailsResponseBody Body;
        
        public UpdateTrackDetailsResponse() {
        }
        
        public UpdateTrackDetailsResponse(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class UpdateTrackDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateTrackDetailsResult;
        
        public UpdateTrackDetailsResponseBody() {
        }
        
        public UpdateTrackDetailsResponseBody(int UpdateTrackDetailsResult) {
            this.UpdateTrackDetailsResult = UpdateTrackDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHospCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHospCode", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.GetHospCodeRequestBody Body;
        
        public GetHospCodeRequest() {
        }
        
        public GetHospCodeRequest(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.GetHospCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetHospCodeRequestBody {
        
        public GetHospCodeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHospCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHospCodeResponse", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.GetHospCodeResponseBody Body;
        
        public GetHospCodeResponse() {
        }
        
        public GetHospCodeResponse(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.GetHospCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class GetHospCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHospCodeResult;
        
        public GetHospCodeResponseBody() {
        }
        
        public GetHospCodeResponseBody(string GetHospCodeResult) {
            this.GetHospCodeResult = GetHospCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrackDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrackDetail", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackDetailRequestBody Body;
        
        public AddTrackDetailRequest() {
        }
        
        public AddTrackDetailRequest(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class AddTrackDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TRACK_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TRACK_DETAIL_FILE_NAME;
        
        public AddTrackDetailRequestBody() {
        }
        
        public AddTrackDetailRequestBody(int TRACK_ID, string TRACK_DETAIL_FILE_NAME) {
            this.TRACK_ID = TRACK_ID;
            this.TRACK_DETAIL_FILE_NAME = TRACK_DETAIL_FILE_NAME;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrackDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrackDetailResponse", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackDetailResponseBody Body;
        
        public AddTrackDetailResponse() {
        }
        
        public AddTrackDetailResponse(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class AddTrackDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddTrackDetailResult;
        
        public AddTrackDetailResponseBody() {
        }
        
        public AddTrackDetailResponseBody(int AddTrackDetailResult) {
            this.AddTrackDetailResult = AddTrackDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTrackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTrack", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackRequestBody Body;
        
        public UpdateTrackRequest() {
        }
        
        public UpdateTrackRequest(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class UpdateTrackRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TrackID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime TRACK_START_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime TRACK_END_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TRACK_FILE_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HOSP_CODE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CLIENT_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ROOT_DIRECTORY;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CLIENT_DIRECTORY;
        
        public UpdateTrackRequestBody() {
        }
        
        public UpdateTrackRequestBody(int TrackID, System.DateTime TRACK_START_TIME, System.DateTime TRACK_END_TIME, string TRACK_FILE_NAME, string HOSP_CODE, string CLIENT_NAME, string ROOT_DIRECTORY, string CLIENT_DIRECTORY) {
            this.TrackID = TrackID;
            this.TRACK_START_TIME = TRACK_START_TIME;
            this.TRACK_END_TIME = TRACK_END_TIME;
            this.TRACK_FILE_NAME = TRACK_FILE_NAME;
            this.HOSP_CODE = HOSP_CODE;
            this.CLIENT_NAME = CLIENT_NAME;
            this.ROOT_DIRECTORY = ROOT_DIRECTORY;
            this.CLIENT_DIRECTORY = CLIENT_DIRECTORY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTrackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTrackResponse", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackResponseBody Body;
        
        public UpdateTrackResponse() {
        }
        
        public UpdateTrackResponse(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class UpdateTrackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateTrackResult;
        
        public UpdateTrackResponseBody() {
        }
        
        public UpdateTrackResponseBody(int UpdateTrackResult) {
            this.UpdateTrackResult = UpdateTrackResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VoiceRecorderSoapChannel : DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.VoiceRecorderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoiceRecorderSoapClient : System.ServiceModel.ClientBase<DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.VoiceRecorderSoap>, DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.VoiceRecorderSoap {
        
        public VoiceRecorderSoapClient() {
        }
        
        public VoiceRecorderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoiceRecorderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceRecorderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceRecorderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackResponse DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.VoiceRecorderSoap.AddTrack(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackRequest request) {
            return base.Channel.AddTrack(request);
        }
        
        public int AddTrack(string USER_ID, string SOURCE_DEVICE, string TRACK_FILE_NAME) {
            DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackRequest inValue = new DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackRequest();
            inValue.Body = new DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackRequestBody();
            inValue.Body.USER_ID = USER_ID;
            inValue.Body.SOURCE_DEVICE = SOURCE_DEVICE;
            inValue.Body.TRACK_FILE_NAME = TRACK_FILE_NAME;
            DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackResponse retVal = ((DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.VoiceRecorderSoap)(this)).AddTrack(inValue);
            return retVal.Body.AddTrackResult;
        }
        
        public int TrackSent(int TRACK_ID) {
            return base.Channel.TrackSent(TRACK_ID);
        }
        
        public int TrackDetailSent(int TRACK_DETAIL_ID) {
            return base.Channel.TrackDetailSent(TRACK_DETAIL_ID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackDetailsResponse DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.VoiceRecorderSoap.UpdateTrackDetails(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackDetailsRequest request) {
            return base.Channel.UpdateTrackDetails(request);
        }
        
        public int UpdateTrackDetails(
                    int TRACK_DETAIL_ID, 
                    string TRACK_FILE_NAME, 
                    string TRACK_DETAIL_SUBJECT, 
                    string TRACK_DETAIL_NOTE, 
                    string USER_ID, 
                    int START_TIME, 
                    int END_TIME, 
                    string HOSP_CODE, 
                    string ACCOUNT_NUMBER, 
                    string MRN, 
                    System.DateTime DOB, 
                    string SOURCE_DEVICE, 
                    string CLIENT_NAME, 
                    string ROOT_DIRECTORY, 
                    string CLIENT_DIRECTORY, 
                    string FILE_PATH) {
            DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackDetailsRequest inValue = new DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackDetailsRequest();
            inValue.Body = new DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackDetailsRequestBody();
            inValue.Body.TRACK_DETAIL_ID = TRACK_DETAIL_ID;
            inValue.Body.TRACK_FILE_NAME = TRACK_FILE_NAME;
            inValue.Body.TRACK_DETAIL_SUBJECT = TRACK_DETAIL_SUBJECT;
            inValue.Body.TRACK_DETAIL_NOTE = TRACK_DETAIL_NOTE;
            inValue.Body.USER_ID = USER_ID;
            inValue.Body.START_TIME = START_TIME;
            inValue.Body.END_TIME = END_TIME;
            inValue.Body.HOSP_CODE = HOSP_CODE;
            inValue.Body.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            inValue.Body.MRN = MRN;
            inValue.Body.DOB = DOB;
            inValue.Body.SOURCE_DEVICE = SOURCE_DEVICE;
            inValue.Body.CLIENT_NAME = CLIENT_NAME;
            inValue.Body.ROOT_DIRECTORY = ROOT_DIRECTORY;
            inValue.Body.CLIENT_DIRECTORY = CLIENT_DIRECTORY;
            inValue.Body.FILE_PATH = FILE_PATH;
            DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackDetailsResponse retVal = ((DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.VoiceRecorderSoap)(this)).UpdateTrackDetails(inValue);
            return retVal.Body.UpdateTrackDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.GetHospCodeResponse DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.VoiceRecorderSoap.GetHospCode(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.GetHospCodeRequest request) {
            return base.Channel.GetHospCode(request);
        }
        
        public string GetHospCode() {
            DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.GetHospCodeRequest inValue = new DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.GetHospCodeRequest();
            inValue.Body = new DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.GetHospCodeRequestBody();
            DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.GetHospCodeResponse retVal = ((DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.VoiceRecorderSoap)(this)).GetHospCode(inValue);
            return retVal.Body.GetHospCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackDetailResponse DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.VoiceRecorderSoap.AddTrackDetail(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackDetailRequest request) {
            return base.Channel.AddTrackDetail(request);
        }
        
        public int AddTrackDetail(int TRACK_ID, string TRACK_DETAIL_FILE_NAME) {
            DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackDetailRequest inValue = new DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackDetailRequest();
            inValue.Body = new DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackDetailRequestBody();
            inValue.Body.TRACK_ID = TRACK_ID;
            inValue.Body.TRACK_DETAIL_FILE_NAME = TRACK_DETAIL_FILE_NAME;
            DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.AddTrackDetailResponse retVal = ((DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.VoiceRecorderSoap)(this)).AddTrackDetail(inValue);
            return retVal.Body.AddTrackDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackResponse DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.VoiceRecorderSoap.UpdateTrack(DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackRequest request) {
            return base.Channel.UpdateTrack(request);
        }
        
        public int UpdateTrack(int TrackID, System.DateTime TRACK_START_TIME, System.DateTime TRACK_END_TIME, string TRACK_FILE_NAME, string HOSP_CODE, string CLIENT_NAME, string ROOT_DIRECTORY, string CLIENT_DIRECTORY) {
            DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackRequest inValue = new DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackRequest();
            inValue.Body = new DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackRequestBody();
            inValue.Body.TrackID = TrackID;
            inValue.Body.TRACK_START_TIME = TRACK_START_TIME;
            inValue.Body.TRACK_END_TIME = TRACK_END_TIME;
            inValue.Body.TRACK_FILE_NAME = TRACK_FILE_NAME;
            inValue.Body.HOSP_CODE = HOSP_CODE;
            inValue.Body.CLIENT_NAME = CLIENT_NAME;
            inValue.Body.ROOT_DIRECTORY = ROOT_DIRECTORY;
            inValue.Body.CLIENT_DIRECTORY = CLIENT_DIRECTORY;
            DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.UpdateTrackResponse retVal = ((DCSGlobal.Medical.VoiceRecoder.srVoiceRecorder.VoiceRecorderSoap)(this)).UpdateTrack(inValue);
            return retVal.Body.UpdateTrackResult;
        }
    }
}
