//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manual_test_app.EDI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manual_test_app.EDI.RES", typeof(RES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=10.34.1.190;Initial Catalog=al60_rchp_prod;Persist Security Info=True;User ID=suresh;Password=suresh247.
        /// </summary>
        internal static string ghinckley {
            get {
                return ResourceManager.GetString("ghinckley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISA*00* *00* *ZZ*
        ///TPU
        ///nique
        ///ID
        ///*
        ///33
        ///*
        ///95216
        ///*110311*1136*
        ///^
        ///*
        ///00501
        ///*31118050 *0*P*:~
        ///GS*HS*
        ///TPUNIQUEID
        ///*
        ///95216
        ///*20110311*1136*31118050*
        ///005010X279A1
        ///~
        ///ST*270*0001
        ///*005010X279
        ///A1
        ///~
        ///BHT*0022*13*31118050*20110
        ///408
        ///*1136~
        ///HL*1**20*1~
        ///NM1*PR*2*UPMC HEALTH PLAN*****PI*
        ///111111111
        ///~
        ///HL*2*1*21*1~
        ///NM1*1P*
        ///1
        ///*
        ///LINE
        ///*
        ///WILLIAM
        ///*
        ///J
        ///***
        ///XX
        ///*
        ///2222222222
        ///~
        ///HL*3*2*22*0~
        ///TRN*1*K1211624
        ///~
        ///NM1*IL*1*
        ///KENT
        ///*
        ///CLARK
        ///*
        ///S
        ///***MI*
        ///00044444404
        ///~
        ///REF*SY*
        ///444444444
        ///~
        ///DMG*D8*
        ///19 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s270 {
            get {
                return ResourceManager.GetString("s270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISA*00*          *00*          *ZZ*CMS            *ZZ*dcsglo         *130425*1740*^*00501*039285424*0*P*|~
        ///GS*HB*CMS*dcsglo*20130425*17400000*1*X*005010X279A1~
        ///ST*271*0001*005010X279A1~
        ///BHT*0022*11*E8438828A66942C*20130425*17405661~
        ///HL*1**20*1~
        ///NM1*PR*2*CMS*****PI*CMS~
        ///PER*IC**UR*http://www.cms.gov/HETSHelp/*UR*http://www.cms.gov/center/provider.asp~
        ///HL*2*1*21*1~
        ///NM1*1P*2*LIMA MEMORIAL HLTH SYS*****XX*1336144732~
        ///HL*3*2*22*0~
        ///TRN*2*E8438828A66942C*9954719251~
        ///NM1*IL*1*LEONARD*ELIZABETH*T***MI*065 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s271 {
            get {
                return ResourceManager.GetString("s271", resourceCulture);
            }
        }
    }
}
