//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "AlbamaMedicaidproxy.CoreRealTime")]
    public interface CoreRealTime
    {

        // CODEGEN: Generating message contract since the operation RealTimeTransaction is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "RealTimeTransaction", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.RealTimeTransactionResponse RealTimeTransaction(DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.RealTimeTransactionRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class COREEnvelopeRealTimeRequest : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string payloadTypeField;

        private string processingModeField;

        private string payloadIDField;

        private string timeStampField;

        private string senderIDField;

        private string receiverIDField;

        private string cORERuleVersionField;

        private string payloadField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string PayloadType
        {
            get
            {
                return this.payloadTypeField;
            }
            set
            {
                this.payloadTypeField = value;
                this.RaisePropertyChanged("PayloadType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string ProcessingMode
        {
            get
            {
                return this.processingModeField;
            }
            set
            {
                this.processingModeField = value;
                this.RaisePropertyChanged("ProcessingMode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string PayloadID
        {
            get
            {
                return this.payloadIDField;
            }
            set
            {
                this.payloadIDField = value;
                this.RaisePropertyChanged("PayloadID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
                this.RaisePropertyChanged("SenderID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string ReceiverID
        {
            get
            {
                return this.receiverIDField;
            }
            set
            {
                this.receiverIDField = value;
                this.RaisePropertyChanged("ReceiverID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string CORERuleVersion
        {
            get
            {
                return this.cORERuleVersionField;
            }
            set
            {
                this.cORERuleVersionField = value;
                this.RaisePropertyChanged("CORERuleVersion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
                this.RaisePropertyChanged("Payload");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class COREEnvelopeRealTimeResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string payloadTypeField;

        private string processingModeField;

        private string payloadIDField;

        private string timeStampField;

        private string senderIDField;

        private string receiverIDField;

        private string cORERuleVersionField;

        private string payloadField;

        private string errorCodeField;

        private string errorMessageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string PayloadType
        {
            get
            {
                return this.payloadTypeField;
            }
            set
            {
                this.payloadTypeField = value;
                this.RaisePropertyChanged("PayloadType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string ProcessingMode
        {
            get
            {
                return this.processingModeField;
            }
            set
            {
                this.processingModeField = value;
                this.RaisePropertyChanged("ProcessingMode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string PayloadID
        {
            get
            {
                return this.payloadIDField;
            }
            set
            {
                this.payloadIDField = value;
                this.RaisePropertyChanged("PayloadID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
                this.RaisePropertyChanged("SenderID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string ReceiverID
        {
            get
            {
                return this.receiverIDField;
            }
            set
            {
                this.receiverIDField = value;
                this.RaisePropertyChanged("ReceiverID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string CORERuleVersion
        {
            get
            {
                return this.cORERuleVersionField;
            }
            set
            {
                this.cORERuleVersionField = value;
                this.RaisePropertyChanged("CORERuleVersion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
                this.RaisePropertyChanged("Payload");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RealTimeTransactionRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order = 0)]
        public DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.COREEnvelopeRealTimeRequest COREEnvelopeRealTimeRequest;

        public RealTimeTransactionRequest()
        {
        }

        public RealTimeTransactionRequest(DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.COREEnvelopeRealTimeRequest COREEnvelopeRealTimeRequest)
        {
            this.COREEnvelopeRealTimeRequest = COREEnvelopeRealTimeRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RealTimeTransactionResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order = 0)]
        public DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.COREEnvelopeRealTimeResponse COREEnvelopeRealTimeResponse;

        public RealTimeTransactionResponse()
        {
        }

        public RealTimeTransactionResponse(DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.COREEnvelopeRealTimeResponse COREEnvelopeRealTimeResponse)
        {
            this.COREEnvelopeRealTimeResponse = COREEnvelopeRealTimeResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CoreRealTimeChannel : DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.CoreRealTime, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreRealTimeClient : System.ServiceModel.ClientBase<DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.CoreRealTime>, DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.CoreRealTime
    {

        public CoreRealTimeClient()
        {
        }

        public CoreRealTimeClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public CoreRealTimeClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CoreRealTimeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CoreRealTimeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.RealTimeTransactionResponse DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.CoreRealTime.RealTimeTransaction(DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.RealTimeTransactionRequest request)
        {
            return base.Channel.RealTimeTransaction(request);
        }

        public DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.COREEnvelopeRealTimeResponse RealTimeTransaction(DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.COREEnvelopeRealTimeRequest COREEnvelopeRealTimeRequest)
        {
            DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.RealTimeTransactionRequest inValue = new DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.RealTimeTransactionRequest();
            inValue.COREEnvelopeRealTimeRequest = COREEnvelopeRealTimeRequest;
            DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.RealTimeTransactionResponse retVal = ((DCSGlobal.EDI.Comunications.AlbamaMedicaidproxy.CoreRealTime)(this)).RealTimeTransaction(inValue);
            return retVal.COREEnvelopeRealTimeResponse;
        }
    }
}
