using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
  
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSGlobal.EDI.Comunications.DEMCDWrapper
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "COREEnvelopeRealTimeRequest", Namespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    [System.SerializableAttribute()]
    public partial class COREEnvelopeRealTimeRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string PayloadTypeField;

        private string ProcessingModeField;

        private string PayloadIDField;

        private string TimeStampField;

        private string SenderIDField;

        private string ReceiverIDField;

        private string CORERuleVersionField;

        private string PayloadField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        public string PayloadType
        {
            get
            {
                return this.PayloadTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PayloadTypeField, value) != true))
                {
                    this.PayloadTypeField = value;
                    this.RaisePropertyChanged("PayloadType");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        public string ProcessingMode
        {
            get
            {
                return this.ProcessingModeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ProcessingModeField, value) != true))
                {
                    this.ProcessingModeField = value;
                    this.RaisePropertyChanged("ProcessingMode");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 2)]
        public string PayloadID
        {
            get
            {
                return this.PayloadIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PayloadIDField, value) != true))
                {
                    this.PayloadIDField = value;
                    this.RaisePropertyChanged("PayloadID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 3)]
        public string TimeStamp
        {
            get
            {
                return this.TimeStampField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true))
                {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 4)]
        public string SenderID
        {
            get
            {
                return this.SenderIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SenderIDField, value) != true))
                {
                    this.SenderIDField = value;
                    this.RaisePropertyChanged("SenderID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 5)]
        public string ReceiverID
        {
            get
            {
                return this.ReceiverIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ReceiverIDField, value) != true))
                {
                    this.ReceiverIDField = value;
                    this.RaisePropertyChanged("ReceiverID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 6)]
        public string CORERuleVersion
        {
            get
            {
                return this.CORERuleVersionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CORERuleVersionField, value) != true))
                {
                    this.CORERuleVersionField = value;
                    this.RaisePropertyChanged("CORERuleVersion");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 7)]
        public string Payload
        {
            get
            {
                return this.PayloadField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PayloadField, value) != true))
                {
                    this.PayloadField = value;
                    this.RaisePropertyChanged("Payload");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "COREEnvelopeRealTimeResponse", Namespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    [System.SerializableAttribute()]
    public partial class COREEnvelopeRealTimeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string PayloadTypeField;

        private string ProcessingModeField;

        private string PayloadIDField;

        private string TimeStampField;

        private string SenderIDField;

        private string ReceiverIDField;

        private string CORERuleVersionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadField;

        private string ErrorCodeField;

        private string ErrorMessageField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        public string PayloadType
        {
            get
            {
                return this.PayloadTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PayloadTypeField, value) != true))
                {
                    this.PayloadTypeField = value;
                    this.RaisePropertyChanged("PayloadType");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        public string ProcessingMode
        {
            get
            {
                return this.ProcessingModeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ProcessingModeField, value) != true))
                {
                    this.ProcessingModeField = value;
                    this.RaisePropertyChanged("ProcessingMode");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 2)]
        public string PayloadID
        {
            get
            {
                return this.PayloadIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PayloadIDField, value) != true))
                {
                    this.PayloadIDField = value;
                    this.RaisePropertyChanged("PayloadID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 3)]
        public string TimeStamp
        {
            get
            {
                return this.TimeStampField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true))
                {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 4)]
        public string SenderID
        {
            get
            {
                return this.SenderIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SenderIDField, value) != true))
                {
                    this.SenderIDField = value;
                    this.RaisePropertyChanged("SenderID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 5)]
        public string ReceiverID
        {
            get
            {
                return this.ReceiverIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ReceiverIDField, value) != true))
                {
                    this.ReceiverIDField = value;
                    this.RaisePropertyChanged("ReceiverID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 6)]
        public string CORERuleVersion
        {
            get
            {
                return this.CORERuleVersionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CORERuleVersionField, value) != true))
                {
                    this.CORERuleVersionField = value;
                    this.RaisePropertyChanged("CORERuleVersion");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string Payload
        {
            get
            {
                return this.PayloadField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PayloadField, value) != true))
                {
                    this.PayloadField = value;
                    this.RaisePropertyChanged("Payload");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 8)]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true))
                {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 9)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true))
                {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "DEMCDWrapper.ICoreRealTime")]
    public interface ICoreRealTime
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICoreRealTime/RealTimeTransaction", ReplyAction = "http://tempuri.org/ICoreRealTime/RealTimeTransactionResponse")]
        DCSGlobal.EDI.Comunications.DEMCDWrapper.COREEnvelopeRealTimeResponse RealTimeTransaction(DCSGlobal.EDI.Comunications.DEMCDWrapper.COREEnvelopeRealTimeRequest Request);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoreRealTimeChannel : DCSGlobal.EDI.Comunications.DEMCDWrapper.ICoreRealTime, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreRealTimeClient : System.ServiceModel.ClientBase<DCSGlobal.EDI.Comunications.DEMCDWrapper.ICoreRealTime>, DCSGlobal.EDI.Comunications.DEMCDWrapper.ICoreRealTime
    {

        public CoreRealTimeClient()
        {
        }

        public CoreRealTimeClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public CoreRealTimeClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CoreRealTimeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CoreRealTimeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public DCSGlobal.EDI.Comunications.DEMCDWrapper.COREEnvelopeRealTimeResponse RealTimeTransaction(DCSGlobal.EDI.Comunications.DEMCDWrapper.COREEnvelopeRealTimeRequest Request)
        {
            return base.Channel.RealTimeTransaction(Request);
        }
    }
}
