using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DCSGlobal.BusinessRules.Logging;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSGlobal.EDI.Comunications.MainMedicaidProxy
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", ConfigurationName = "MainMedicaidProxy.ISOAPService")]
    public interface ISOAPService
    {

        // CODEGEN: Generating message contract since the wrapper name (COREEnvelopeRealTimeRequest) of message RealTimeRequestMessage does not match the default value (RealTimeTransaction)
        [System.ServiceModel.OperationContractAttribute(Action = "RealTimeTransaction", ReplyAction = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd/ISOAPService/RealTimeTransactionR" +
            "esponse")]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.RealTimeResponseMessage RealTimeTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.RealTimeRequestMessage request);

        // CODEGEN: Generating message contract since the wrapper name (COREEnvelopeBatchSubmission) of message BatchSubmissionMessage does not match the default value (BatchSubmitTransaction)
        [System.ServiceModel.OperationContractAttribute(Action = "BatchSubmitTransaction", ReplyAction = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd/ISOAPService/BatchSubmitTransacti" +
            "onResponse")]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionResponseMessage BatchSubmitTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionMessage request);

        // CODEGEN: Generating message contract since the wrapper name (COREEnvelopeBatchSubmissionAckRetrievalRequest) of message BatchSubmissionAckRetrievalRequestMessage does not match the default value (BatchSubmitAckRetrievalTransaction)
        [System.ServiceModel.OperationContractAttribute(Action = "BatchSubmitAckRetrievalTransaction", ReplyAction = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd/ISOAPService/BatchSubmitAckRetrie" +
            "valTransactionResponse")]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionAckRetrievalResponseMessage BatchSubmitAckRetrievalTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionAckRetrievalRequestMessage request);

        // CODEGEN: Generating message contract since the wrapper name (COREEnvelopeBatchResultsRetrievalRequest) of message BatchResultsRetrievalRequestMessage does not match the default value (BatchResultsRetrievalTransaction)
        [System.ServiceModel.OperationContractAttribute(Action = "BatchResultsRetrievalTransaction", ReplyAction = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd/ISOAPService/BatchResultsRetrieva" +
            "lTransactionResponse")]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalResponseMessage BatchResultsRetrievalTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalRequestMessage request);

        // CODEGEN: Generating message contract since the wrapper name (COREEnvelopeBatchResultsAckSubmission) of message BatchResultsAckSubmissionMessage does not match the default value (BatchResultsAckSubmitTransaction)
        [System.ServiceModel.OperationContractAttribute(Action = "BatchResultsAckSubmitTransaction", ReplyAction = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd/ISOAPService/BatchResultsAckSubmi" +
            "tTransactionResponse")]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionResponseMessage BatchResultsAckSubmitTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionMessage request);

        // CODEGEN: Generating message contract since the wrapper name (COREEnvelopeBatchSubmission) of message BatchSubmissionMessage does not match the default value (GenericBatchSubmissionTransaction)
        [System.ServiceModel.OperationContractAttribute(Action = "GenericBatchSubmissionTransaction", ReplyAction = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd/ISOAPService/GenericBatchSubmissi" +
            "onTransactionResponse")]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionResponseMessage GenericBatchSubmissionTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionMessage request);

        // CODEGEN: Generating message contract since the wrapper name (COREEnvelopeBatchResultsRetrievalRequest) of message BatchResultsRetrievalRequestMessage does not match the default value (GenericBatchRetrievalTransaction)
        [System.ServiceModel.OperationContractAttribute(Action = "GenericBatchRetrievalTransaction", ReplyAction = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd/ISOAPService/GenericBatchRetrieva" +
            "lTransactionResponse")]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalResponseMessage GenericBatchRetrievalTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalRequestMessage request);

        // CODEGEN: Generating message contract since the wrapper name (COREEnvelopeBatchResultsAckSubmission) of message BatchResultsAckSubmissionMessage does not match the default value (GenericBatchReceiptConfirmationTransaction)
        [System.ServiceModel.OperationContractAttribute(Action = "GenericBatchReceiptConfirmationTransaction", ReplyAction = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd/ISOAPService/GenericBatchReceiptC" +
            "onfirmationTransactionResponse")]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionResponseMessage GenericBatchReceiptConfirmationTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionMessage request);

        // CODEGEN: Generating message contract since the wrapper name (COREEnvelopePayloadReceiptConfirmationRequestMessage) of message PayloadReceiptConfirmationRequestMessage does not match the default value (PayloadReceiptConfirmation)
        [System.ServiceModel.OperationContractAttribute(Action = "PayloadReceiptConfirmation", ReplyAction = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd/ISOAPService/PayloadReceiptConfir" +
            "mationResponse")]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.PayloadReceiptConfirmationResponseMessage PayloadReceiptConfirmation(DCSGlobal.EDI.Comunications.MainMedicaidProxy.PayloadReceiptConfirmationRequestMessage request);

        // CODEGEN: Generating message contract since the wrapper name (COREEnvelopeGenericBatchRetrievalRequestMessage) of message GenericBatchRetrievalRequestMessage does not match the default value (GenericBatchRetrievalRequest)
        [System.ServiceModel.OperationContractAttribute(Action = "GenericBatchRetrievalRequest", ReplyAction = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd/ISOAPService/GenericBatchRetrieva" +
            "lRequestResponse")]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.GenericBatchRetrievalResponseMessage GenericBatchRetrievalRequest(DCSGlobal.EDI.Comunications.MainMedicaidProxy.GenericBatchRetrievalRequestMessage request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopeRealTimeRequest", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class RealTimeRequestMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string Payload;

        public RealTimeRequestMessage()
        {
        }

        public RealTimeRequestMessage(string PayloadType, string ProcessingMode, string PayloadID, string TimeStamp, string SenderID, string ReceiverID, string CORERuleVersion, string Payload)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.Payload = Payload;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopeRealTimeResponse", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class RealTimeResponseMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string Payload;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public string ErrorCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 9)]
        public string ErrorMessage;

        public RealTimeResponseMessage()
        {
        }

        public RealTimeResponseMessage(string PayloadType, string ProcessingMode, string PayloadID, string TimeStamp, string SenderID, string ReceiverID, string CORERuleVersion, string Payload, string ErrorCode, string ErrorMessage)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.Payload = Payload;
            this.ErrorCode = ErrorCode;
            this.ErrorMessage = ErrorMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopeBatchSubmission", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class BatchSubmissionMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public int PayloadLength;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public string CheckSum;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 9)]
        public byte[] Payload;

        public BatchSubmissionMessage()
        {
        }

        public BatchSubmissionMessage(string PayloadType, string ProcessingMode, string PayloadID, int PayloadLength, string TimeStamp, string SenderID, string ReceiverID, string CORERuleVersion, string CheckSum, byte[] Payload)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.PayloadLength = PayloadLength;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.CheckSum = CheckSum;
            this.Payload = Payload;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopeBatchSubmissionResponse", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class BatchSubmissionResponseMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public int PayloadLength;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public string CheckSum;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 9)]
        public byte[] Payload;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 10)]
        public string ErrorCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 11)]
        public string ErrorMessage;

        public BatchSubmissionResponseMessage()
        {
        }

        public BatchSubmissionResponseMessage(string PayloadType, string ProcessingMode, string PayloadID, int PayloadLength, string TimeStamp, string SenderID, string ReceiverID, string CORERuleVersion, string CheckSum, byte[] Payload, string ErrorCode, string ErrorMessage)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.PayloadLength = PayloadLength;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.CheckSum = CheckSum;
            this.Payload = Payload;
            this.ErrorCode = ErrorCode;
            this.ErrorMessage = ErrorMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopeBatchSubmissionAckRetrievalRequest", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class BatchSubmissionAckRetrievalRequestMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public int PayloadLength;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public string CheckSum;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 9)]
        public byte[] Payload;

        public BatchSubmissionAckRetrievalRequestMessage()
        {
        }

        public BatchSubmissionAckRetrievalRequestMessage(string PayloadType, string ProcessingMode, string PayloadID, int PayloadLength, string TimeStamp, string SenderID, string ReceiverID, string CORERuleVersion, string CheckSum, byte[] Payload)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.PayloadLength = PayloadLength;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.CheckSum = CheckSum;
            this.Payload = Payload;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopeBatchSubmissionAckRetrievalResponse", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class BatchSubmissionAckRetrievalResponseMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public int PayloadLength;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public string CheckSum;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 9)]
        public byte[] Payload;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 10)]
        public string ErrorCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 11)]
        public string ErrorMessage;

        public BatchSubmissionAckRetrievalResponseMessage()
        {
        }

        public BatchSubmissionAckRetrievalResponseMessage(string PayloadType, string ProcessingMode, string PayloadID, int PayloadLength, string TimeStamp, string SenderID, string ReceiverID, string CORERuleVersion, string CheckSum, byte[] Payload, string ErrorCode, string ErrorMessage)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.PayloadLength = PayloadLength;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.CheckSum = CheckSum;
            this.Payload = Payload;
            this.ErrorCode = ErrorCode;
            this.ErrorMessage = ErrorMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopeBatchResultsRetrievalRequest", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class BatchResultsRetrievalRequestMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public int PayloadLength;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public string CheckSum;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 9)]
        public byte[] Payload;

        public BatchResultsRetrievalRequestMessage()
        {
        }

        public BatchResultsRetrievalRequestMessage(string PayloadType, string ProcessingMode, string PayloadID, int PayloadLength, string TimeStamp, string SenderID, string ReceiverID, string CORERuleVersion, string CheckSum, byte[] Payload)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.PayloadLength = PayloadLength;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.CheckSum = CheckSum;
            this.Payload = Payload;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopeBatchResultsRetrievalResponse", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class BatchResultsRetrievalResponseMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public int PayloadLength;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public string CheckSum;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 9)]
        public byte[] Payload;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 10)]
        public string ErrorCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 11)]
        public string ErrorMessage;

        public BatchResultsRetrievalResponseMessage()
        {
        }

        public BatchResultsRetrievalResponseMessage(string PayloadType, string ProcessingMode, string PayloadID, int PayloadLength, string TimeStamp, string SenderID, string ReceiverID, string CORERuleVersion, string CheckSum, byte[] Payload, string ErrorCode, string ErrorMessage)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.PayloadLength = PayloadLength;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.CheckSum = CheckSum;
            this.Payload = Payload;
            this.ErrorCode = ErrorCode;
            this.ErrorMessage = ErrorMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopeBatchResultsAckSubmission", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class BatchResultsAckSubmissionMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public int PayloadLength;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public string CheckSum;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 9)]
        public byte[] Payload;

        public BatchResultsAckSubmissionMessage()
        {
        }

        public BatchResultsAckSubmissionMessage(string PayloadType, string ProcessingMode, string PayloadID, int PayloadLength, string TimeStamp, string SenderID, string ReceiverID, string CORERuleVersion, string CheckSum, byte[] Payload)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.PayloadLength = PayloadLength;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.CheckSum = CheckSum;
            this.Payload = Payload;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopeBatchResultsAckSubmissionResponse", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class BatchResultsAckSubmissionResponseMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public int PayloadLength;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public string CheckSum;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 9)]
        public byte[] Payload;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 10)]
        public string ErrorCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 11)]
        public string ErrorMessage;

        public BatchResultsAckSubmissionResponseMessage()
        {
        }

        public BatchResultsAckSubmissionResponseMessage(string PayloadType, string ProcessingMode, string PayloadID, int PayloadLength, string TimeStamp, string SenderID, string ReceiverID, string CORERuleVersion, string CheckSum, byte[] Payload, string ErrorCode, string ErrorMessage)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.PayloadLength = PayloadLength;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.CheckSum = CheckSum;
            this.Payload = Payload;
            this.ErrorCode = ErrorCode;
            this.ErrorMessage = ErrorMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopePayloadReceiptConfirmationRequestMessage", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class PayloadReceiptConfirmationRequestMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string CheckSum;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public int PayloadLength;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 9)]
        public byte[] Payload;

        public PayloadReceiptConfirmationRequestMessage()
        {
        }

        public PayloadReceiptConfirmationRequestMessage(string PayloadType, string ProcessingMode, string PayloadID, string TimeStamp, string SenderID, string ReceiverID, string CORERuleVersion, string CheckSum, int PayloadLength, byte[] Payload)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.CheckSum = CheckSum;
            this.PayloadLength = PayloadLength;
            this.Payload = Payload;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopePayloadReceiptConfirmationResponseMessage", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class PayloadReceiptConfirmationResponseMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string ErrorCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public string ErrorMessage;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 9)]
        public string TPATransactionID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 10)]
        public string DiagnositicInfo;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 11)]
        public string EDIGWMessage;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 12)]
        public string EDIGWMessageID;

        public PayloadReceiptConfirmationResponseMessage()
        {
        }

        public PayloadReceiptConfirmationResponseMessage(string PayloadType, string ProcessingMode, string PayloadID, string TimeStamp, string SenderID, string ReceiverID, string CORERuleVersion, string ErrorCode, string ErrorMessage, string TPATransactionID, string DiagnositicInfo, string EDIGWMessage, string EDIGWMessageID)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.ErrorCode = ErrorCode;
            this.ErrorMessage = ErrorMessage;
            this.TPATransactionID = TPATransactionID;
            this.DiagnositicInfo = DiagnositicInfo;
            this.EDIGWMessage = EDIGWMessage;
            this.EDIGWMessageID = EDIGWMessageID;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopeGenericBatchRetrievalRequestMessage", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class GenericBatchRetrievalRequestMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string CheckSum;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public int PayloadLength;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 9)]
        public byte[] Payload;

        public GenericBatchRetrievalRequestMessage()
        {
        }

        public GenericBatchRetrievalRequestMessage(string PayloadType, string ProcessingMode, string PayloadID, string TimeStamp, string SenderID, string ReceiverID, string CORERuleVersion, string CheckSum, int PayloadLength, byte[] Payload)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.CheckSum = CheckSum;
            this.PayloadLength = PayloadLength;
            this.Payload = Payload;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "COREEnvelopeGenericBatchRetrievalResponseMessage", WrapperNamespace = "http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", IsWrapped = true)]
    public partial class GenericBatchRetrievalResponseMessage
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string PayloadType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string ProcessingMode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string PayloadID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public string TimeStamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string SenderID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string ReceiverID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string CORERuleVersion;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string CheckSum;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public int PayloadLength;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 9)]
        public byte[] Payload;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 10)]
        public string ErrorCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 11)]
        public string ErrorMessage;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 12)]
        public string ServerName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 13)]
        public string TransactionID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 14)]
        public string EDIGWMessageID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 15)]
        public string EDIGWMessage;

        public GenericBatchRetrievalResponseMessage()
        {
        }

        public GenericBatchRetrievalResponseMessage(
                    string PayloadType,
                    string ProcessingMode,
                    string PayloadID,
                    string TimeStamp,
                    string SenderID,
                    string ReceiverID,
                    string CORERuleVersion,
                    string CheckSum,
                    int PayloadLength,
                    byte[] Payload,
                    string ErrorCode,
                    string ErrorMessage,
                    string ServerName,
                    string TransactionID,
                    string EDIGWMessageID,
                    string EDIGWMessage)
        {
            this.PayloadType = PayloadType;
            this.ProcessingMode = ProcessingMode;
            this.PayloadID = PayloadID;
            this.TimeStamp = TimeStamp;
            this.SenderID = SenderID;
            this.ReceiverID = ReceiverID;
            this.CORERuleVersion = CORERuleVersion;
            this.CheckSum = CheckSum;
            this.PayloadLength = PayloadLength;
            this.Payload = Payload;
            this.ErrorCode = ErrorCode;
            this.ErrorMessage = ErrorMessage;
            this.ServerName = ServerName;
            this.TransactionID = TransactionID;
            this.EDIGWMessageID = EDIGWMessageID;
            this.EDIGWMessage = EDIGWMessage;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISOAPServiceChannel : DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SOAPServiceClient : System.ServiceModel.ClientBase<DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService>, DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService
    {

        public SOAPServiceClient()
        {
        }

        public SOAPServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public SOAPServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public SOAPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public SOAPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.RealTimeResponseMessage DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService.RealTimeTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.RealTimeRequestMessage request)
        {
            return base.Channel.RealTimeTransaction(request);
        }
        private string _ConnectionString = string.Empty;
        private logExecption log = new logExecption();
        public string ConnectionString
        {

            set
            {

                _ConnectionString = value;
                log.ConnectionString = value;
            }
        }

        public string RealTimeTransaction(string PayloadType,  string ProcessingMode,ref  string PayloadID,ref  string TimeStamp, string SenderID,  string ReceiverID,  string CORERuleVersion, ref string Payload, out string ErrorMessage)
        {
            log.ConnectionString = _ConnectionString;
            log.ExceptionDetails("MAIN MEDICAID PROXY- Request PayloadID=" + PayloadID, " | Request=" + Payload);

            DCSGlobal.EDI.Comunications.MainMedicaidProxy.RealTimeRequestMessage inValue = new DCSGlobal.EDI.Comunications.MainMedicaidProxy.RealTimeRequestMessage();
            inValue.PayloadType = PayloadType;
            inValue.ProcessingMode = ProcessingMode;
            inValue.PayloadID = PayloadID;
            inValue.TimeStamp = TimeStamp;
            inValue.SenderID = SenderID;
            inValue.ReceiverID = ReceiverID;
            inValue.CORERuleVersion = CORERuleVersion;
            inValue.Payload = Payload;
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.RealTimeResponseMessage retVal = ((DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService)(this)).RealTimeTransaction(inValue);
           // log.ExceptionDetails("MAIN MEDICAID PROXY- Response Original PayloadID=" + PayloadID + " | Return PayloadID= " + retVal.PayloadID, " | ErrorCode=" + retVal.ErrorCode + "  | Response=" + retVal.Payload);
            PayloadType = retVal.PayloadType;
            ProcessingMode = retVal.ProcessingMode;
            PayloadID = retVal.PayloadID;
            TimeStamp = retVal.TimeStamp;
            SenderID = retVal.SenderID;
            ReceiverID = retVal.ReceiverID;
            CORERuleVersion = retVal.CORERuleVersion;
            Payload = retVal.Payload;
            ErrorMessage = retVal.ErrorMessage;
            return retVal.ErrorCode;
        }




        //public string RealTimeTransaction(ref string PayloadType, ref string ProcessingMode, ref string PayloadID, ref string TimeStamp, ref string SenderID, ref string ReceiverID, ref string CORERuleVersion, ref string Payload, out string ErrorMessage)
        //{
        //    log.ConnectionString = _ConnectionString;
        //    log.ExceptionDetails("MAIN MEDICAID PROXY- Request PayloadID=" + PayloadID, " | Request=" + Payload);

        //    DCSGlobal.EDI.Comunications.MainMedicaidProxy.RealTimeRequestMessage inValue = new DCSGlobal.EDI.Comunications.MainMedicaidProxy.RealTimeRequestMessage();
        //    inValue.PayloadType = PayloadType;
        //    inValue.ProcessingMode = ProcessingMode;
        //    inValue.PayloadID = PayloadID;
        //    inValue.TimeStamp = TimeStamp;
        //    inValue.SenderID = SenderID;
        //    inValue.ReceiverID = ReceiverID;
        //    inValue.CORERuleVersion = CORERuleVersion;
        //    inValue.Payload = Payload;
        //    DCSGlobal.EDI.Comunications.MainMedicaidProxy.RealTimeResponseMessage retVal = ((DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService)(this)).RealTimeTransaction(inValue);
        //    log.ExceptionDetails("MAIN MEDICAID PROXY- Response Original PayloadID=" + PayloadID + " | Return PayloadID= " + retVal.PayloadID ," | ErrorCode=" + retVal.ErrorCode  + "  | Response=" + retVal.Payload);
        //    PayloadType = retVal.PayloadType;
        //    ProcessingMode = retVal.ProcessingMode;
        //    PayloadID = retVal.PayloadID;
        //    TimeStamp = retVal.TimeStamp;
        //    SenderID = retVal.SenderID;
        //    ReceiverID = retVal.ReceiverID;
        //    CORERuleVersion = retVal.CORERuleVersion;
        //    Payload = retVal.Payload;
        //    ErrorMessage = retVal.ErrorMessage;
        //    return retVal.ErrorCode;
        //}

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionResponseMessage DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService.BatchSubmitTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionMessage request)
        {
            return base.Channel.BatchSubmitTransaction(request);
        }

        public string BatchSubmitTransaction(ref string PayloadType, ref string ProcessingMode, ref string PayloadID, ref int PayloadLength, ref string TimeStamp, ref string SenderID, ref string ReceiverID, ref string CORERuleVersion, ref string CheckSum, ref byte[] Payload, out string ErrorMessage)
        {
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionMessage inValue = new DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionMessage();
            inValue.PayloadType = PayloadType;
            inValue.ProcessingMode = ProcessingMode;
            inValue.PayloadID = PayloadID;
            inValue.PayloadLength = PayloadLength;
            inValue.TimeStamp = TimeStamp;
            inValue.SenderID = SenderID;
            inValue.ReceiverID = ReceiverID;
            inValue.CORERuleVersion = CORERuleVersion;
            inValue.CheckSum = CheckSum;
            inValue.Payload = Payload;
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionResponseMessage retVal = ((DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService)(this)).BatchSubmitTransaction(inValue);
            PayloadType = retVal.PayloadType;
            ProcessingMode = retVal.ProcessingMode;
            PayloadID = retVal.PayloadID;
            PayloadLength = retVal.PayloadLength;
            TimeStamp = retVal.TimeStamp;
            SenderID = retVal.SenderID;
            ReceiverID = retVal.ReceiverID;
            CORERuleVersion = retVal.CORERuleVersion;
            CheckSum = retVal.CheckSum;
            Payload = retVal.Payload;
            ErrorMessage = retVal.ErrorMessage;
            return retVal.ErrorCode;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionAckRetrievalResponseMessage DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService.BatchSubmitAckRetrievalTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionAckRetrievalRequestMessage request)
        {
            return base.Channel.BatchSubmitAckRetrievalTransaction(request);
        }

        public string BatchSubmitAckRetrievalTransaction(ref string PayloadType, ref string ProcessingMode, ref string PayloadID, ref int PayloadLength, ref string TimeStamp, ref string SenderID, ref string ReceiverID, ref string CORERuleVersion, ref string CheckSum, ref byte[] Payload, out string ErrorMessage)
        {
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionAckRetrievalRequestMessage inValue = new DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionAckRetrievalRequestMessage();
            inValue.PayloadType = PayloadType;
            inValue.ProcessingMode = ProcessingMode;
            inValue.PayloadID = PayloadID;
            inValue.PayloadLength = PayloadLength;
            inValue.TimeStamp = TimeStamp;
            inValue.SenderID = SenderID;
            inValue.ReceiverID = ReceiverID;
            inValue.CORERuleVersion = CORERuleVersion;
            inValue.CheckSum = CheckSum;
            inValue.Payload = Payload;
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionAckRetrievalResponseMessage retVal = ((DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService)(this)).BatchSubmitAckRetrievalTransaction(inValue);
            PayloadType = retVal.PayloadType;
            ProcessingMode = retVal.ProcessingMode;
            PayloadID = retVal.PayloadID;
            PayloadLength = retVal.PayloadLength;
            TimeStamp = retVal.TimeStamp;
            SenderID = retVal.SenderID;
            ReceiverID = retVal.ReceiverID;
            CORERuleVersion = retVal.CORERuleVersion;
            CheckSum = retVal.CheckSum;
            Payload = retVal.Payload;
            ErrorMessage = retVal.ErrorMessage;
            return retVal.ErrorCode;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalResponseMessage DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService.BatchResultsRetrievalTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalRequestMessage request)
        {
            return base.Channel.BatchResultsRetrievalTransaction(request);
        }

        public string BatchResultsRetrievalTransaction(ref string PayloadType, ref string ProcessingMode, ref string PayloadID, ref int PayloadLength, ref string TimeStamp, ref string SenderID, ref string ReceiverID, ref string CORERuleVersion, ref string CheckSum, ref byte[] Payload, out string ErrorMessage)
        {
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalRequestMessage inValue = new DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalRequestMessage();
            inValue.PayloadType = PayloadType;
            inValue.ProcessingMode = ProcessingMode;
            inValue.PayloadID = PayloadID;
            inValue.PayloadLength = PayloadLength;
            inValue.TimeStamp = TimeStamp;
            inValue.SenderID = SenderID;
            inValue.ReceiverID = ReceiverID;
            inValue.CORERuleVersion = CORERuleVersion;
            inValue.CheckSum = CheckSum;
            inValue.Payload = Payload;
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalResponseMessage retVal = ((DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService)(this)).BatchResultsRetrievalTransaction(inValue);
            PayloadType = retVal.PayloadType;
            ProcessingMode = retVal.ProcessingMode;
            PayloadID = retVal.PayloadID;
            PayloadLength = retVal.PayloadLength;
            TimeStamp = retVal.TimeStamp;
            SenderID = retVal.SenderID;
            ReceiverID = retVal.ReceiverID;
            CORERuleVersion = retVal.CORERuleVersion;
            CheckSum = retVal.CheckSum;
            Payload = retVal.Payload;
            ErrorMessage = retVal.ErrorMessage;
            return retVal.ErrorCode;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionResponseMessage DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService.BatchResultsAckSubmitTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionMessage request)
        {
            return base.Channel.BatchResultsAckSubmitTransaction(request);
        }

        public string BatchResultsAckSubmitTransaction(ref string PayloadType, ref string ProcessingMode, ref string PayloadID, ref int PayloadLength, ref string TimeStamp, ref string SenderID, ref string ReceiverID, ref string CORERuleVersion, ref string CheckSum, ref byte[] Payload, out string ErrorMessage)
        {
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionMessage inValue = new DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionMessage();
            inValue.PayloadType = PayloadType;
            inValue.ProcessingMode = ProcessingMode;
            inValue.PayloadID = PayloadID;
            inValue.PayloadLength = PayloadLength;
            inValue.TimeStamp = TimeStamp;
            inValue.SenderID = SenderID;
            inValue.ReceiverID = ReceiverID;
            inValue.CORERuleVersion = CORERuleVersion;
            inValue.CheckSum = CheckSum;
            inValue.Payload = Payload;
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionResponseMessage retVal = ((DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService)(this)).BatchResultsAckSubmitTransaction(inValue);
            PayloadType = retVal.PayloadType;
            ProcessingMode = retVal.ProcessingMode;
            PayloadID = retVal.PayloadID;
            PayloadLength = retVal.PayloadLength;
            TimeStamp = retVal.TimeStamp;
            SenderID = retVal.SenderID;
            ReceiverID = retVal.ReceiverID;
            CORERuleVersion = retVal.CORERuleVersion;
            CheckSum = retVal.CheckSum;
            Payload = retVal.Payload;
            ErrorMessage = retVal.ErrorMessage;
            return retVal.ErrorCode;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionResponseMessage DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService.GenericBatchSubmissionTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionMessage request)
        {
            return base.Channel.GenericBatchSubmissionTransaction(request);
        }

        public string GenericBatchSubmissionTransaction(ref string PayloadType, ref string ProcessingMode, ref string PayloadID, ref int PayloadLength, ref string TimeStamp, ref string SenderID, ref string ReceiverID, ref string CORERuleVersion, ref string CheckSum, ref byte[] Payload, out string ErrorMessage)
        {
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionMessage inValue = new DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionMessage();
            inValue.PayloadType = PayloadType;
            inValue.ProcessingMode = ProcessingMode;
            inValue.PayloadID = PayloadID;
            inValue.PayloadLength = PayloadLength;
            inValue.TimeStamp = TimeStamp;
            inValue.SenderID = SenderID;
            inValue.ReceiverID = ReceiverID;
            inValue.CORERuleVersion = CORERuleVersion;
            inValue.CheckSum = CheckSum;
            inValue.Payload = Payload;
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchSubmissionResponseMessage retVal = ((DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService)(this)).GenericBatchSubmissionTransaction(inValue);
            PayloadType = retVal.PayloadType;
            ProcessingMode = retVal.ProcessingMode;
            PayloadID = retVal.PayloadID;
            PayloadLength = retVal.PayloadLength;
            TimeStamp = retVal.TimeStamp;
            SenderID = retVal.SenderID;
            ReceiverID = retVal.ReceiverID;
            CORERuleVersion = retVal.CORERuleVersion;
            CheckSum = retVal.CheckSum;
            Payload = retVal.Payload;
            ErrorMessage = retVal.ErrorMessage;
            return retVal.ErrorCode;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalResponseMessage DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService.GenericBatchRetrievalTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalRequestMessage request)
        {
            return base.Channel.GenericBatchRetrievalTransaction(request);
        }

        public string GenericBatchRetrievalTransaction(ref string PayloadType, ref string ProcessingMode, ref string PayloadID, ref int PayloadLength, ref string TimeStamp, ref string SenderID, ref string ReceiverID, ref string CORERuleVersion, ref string CheckSum, ref byte[] Payload, out string ErrorMessage)
        {
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalRequestMessage inValue = new DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalRequestMessage();
            inValue.PayloadType = PayloadType;
            inValue.ProcessingMode = ProcessingMode;
            inValue.PayloadID = PayloadID;
            inValue.PayloadLength = PayloadLength;
            inValue.TimeStamp = TimeStamp;
            inValue.SenderID = SenderID;
            inValue.ReceiverID = ReceiverID;
            inValue.CORERuleVersion = CORERuleVersion;
            inValue.CheckSum = CheckSum;
            inValue.Payload = Payload;
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsRetrievalResponseMessage retVal = ((DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService)(this)).GenericBatchRetrievalTransaction(inValue);
            PayloadType = retVal.PayloadType;
            ProcessingMode = retVal.ProcessingMode;
            PayloadID = retVal.PayloadID;
            PayloadLength = retVal.PayloadLength;
            TimeStamp = retVal.TimeStamp;
            SenderID = retVal.SenderID;
            ReceiverID = retVal.ReceiverID;
            CORERuleVersion = retVal.CORERuleVersion;
            CheckSum = retVal.CheckSum;
            Payload = retVal.Payload;
            ErrorMessage = retVal.ErrorMessage;
            return retVal.ErrorCode;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionResponseMessage DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService.GenericBatchReceiptConfirmationTransaction(DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionMessage request)
        {
            return base.Channel.GenericBatchReceiptConfirmationTransaction(request);
        }

        public string GenericBatchReceiptConfirmationTransaction(ref string PayloadType, ref string ProcessingMode, ref string PayloadID, ref int PayloadLength, ref string TimeStamp, ref string SenderID, ref string ReceiverID, ref string CORERuleVersion, ref string CheckSum, ref byte[] Payload, out string ErrorMessage)
        {
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionMessage inValue = new DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionMessage();
            inValue.PayloadType = PayloadType;
            inValue.ProcessingMode = ProcessingMode;
            inValue.PayloadID = PayloadID;
            inValue.PayloadLength = PayloadLength;
            inValue.TimeStamp = TimeStamp;
            inValue.SenderID = SenderID;
            inValue.ReceiverID = ReceiverID;
            inValue.CORERuleVersion = CORERuleVersion;
            inValue.CheckSum = CheckSum;
            inValue.Payload = Payload;
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.BatchResultsAckSubmissionResponseMessage retVal = ((DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService)(this)).GenericBatchReceiptConfirmationTransaction(inValue);
            PayloadType = retVal.PayloadType;
            ProcessingMode = retVal.ProcessingMode;
            PayloadID = retVal.PayloadID;
            PayloadLength = retVal.PayloadLength;
            TimeStamp = retVal.TimeStamp;
            SenderID = retVal.SenderID;
            ReceiverID = retVal.ReceiverID;
            CORERuleVersion = retVal.CORERuleVersion;
            CheckSum = retVal.CheckSum;
            Payload = retVal.Payload;
            ErrorMessage = retVal.ErrorMessage;
            return retVal.ErrorCode;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.PayloadReceiptConfirmationResponseMessage DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService.PayloadReceiptConfirmation(DCSGlobal.EDI.Comunications.MainMedicaidProxy.PayloadReceiptConfirmationRequestMessage request)
        {
            return base.Channel.PayloadReceiptConfirmation(request);
        }

        public string PayloadReceiptConfirmation(ref string PayloadType, ref string ProcessingMode, ref string PayloadID, ref string TimeStamp, ref string SenderID, ref string ReceiverID, ref string CORERuleVersion, string CheckSum, int PayloadLength, byte[] Payload, out string ErrorMessage, out string TPATransactionID, out string DiagnositicInfo, out string EDIGWMessage, out string EDIGWMessageID)
        {
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.PayloadReceiptConfirmationRequestMessage inValue = new DCSGlobal.EDI.Comunications.MainMedicaidProxy.PayloadReceiptConfirmationRequestMessage();
            inValue.PayloadType = PayloadType;
            inValue.ProcessingMode = ProcessingMode;
            inValue.PayloadID = PayloadID;
            inValue.TimeStamp = TimeStamp;
            inValue.SenderID = SenderID;
            inValue.ReceiverID = ReceiverID;
            inValue.CORERuleVersion = CORERuleVersion;
            inValue.CheckSum = CheckSum;
            inValue.PayloadLength = PayloadLength;
            inValue.Payload = Payload;
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.PayloadReceiptConfirmationResponseMessage retVal = ((DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService)(this)).PayloadReceiptConfirmation(inValue);
            PayloadType = retVal.PayloadType;
            ProcessingMode = retVal.ProcessingMode;
            PayloadID = retVal.PayloadID;
            TimeStamp = retVal.TimeStamp;
            SenderID = retVal.SenderID;
            ReceiverID = retVal.ReceiverID;
            CORERuleVersion = retVal.CORERuleVersion;
            ErrorMessage = retVal.ErrorMessage;
            TPATransactionID = retVal.TPATransactionID;
            DiagnositicInfo = retVal.DiagnositicInfo;
            EDIGWMessage = retVal.EDIGWMessage;
            EDIGWMessageID = retVal.EDIGWMessageID;
            return retVal.ErrorCode;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.EDI.Comunications.MainMedicaidProxy.GenericBatchRetrievalResponseMessage DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService.GenericBatchRetrievalRequest(DCSGlobal.EDI.Comunications.MainMedicaidProxy.GenericBatchRetrievalRequestMessage request)
        {
            return base.Channel.GenericBatchRetrievalRequest(request);
        }

        public string GenericBatchRetrievalRequest(ref string PayloadType, ref string ProcessingMode, ref string PayloadID, ref string TimeStamp, ref string SenderID, ref string ReceiverID, ref string CORERuleVersion, ref string CheckSum, ref int PayloadLength, ref byte[] Payload, out string ErrorMessage, out string ServerName, out string TransactionID, out string EDIGWMessageID, out string EDIGWMessage)
        {
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.GenericBatchRetrievalRequestMessage inValue = new DCSGlobal.EDI.Comunications.MainMedicaidProxy.GenericBatchRetrievalRequestMessage();
            inValue.PayloadType = PayloadType;
            inValue.ProcessingMode = ProcessingMode;
            inValue.PayloadID = PayloadID;
            inValue.TimeStamp = TimeStamp;
            inValue.SenderID = SenderID;
            inValue.ReceiverID = ReceiverID;
            inValue.CORERuleVersion = CORERuleVersion;
            inValue.CheckSum = CheckSum;
            inValue.PayloadLength = PayloadLength;
            inValue.Payload = Payload;
            DCSGlobal.EDI.Comunications.MainMedicaidProxy.GenericBatchRetrievalResponseMessage retVal = ((DCSGlobal.EDI.Comunications.MainMedicaidProxy.ISOAPService)(this)).GenericBatchRetrievalRequest(inValue);
            PayloadType = retVal.PayloadType;
            ProcessingMode = retVal.ProcessingMode;
            PayloadID = retVal.PayloadID;
            TimeStamp = retVal.TimeStamp;
            SenderID = retVal.SenderID;
            ReceiverID = retVal.ReceiverID;
            CORERuleVersion = retVal.CORERuleVersion;
            CheckSum = retVal.CheckSum;
            PayloadLength = retVal.PayloadLength;
            Payload = retVal.Payload;
            ErrorMessage = retVal.ErrorMessage;
            ServerName = retVal.ServerName;
            TransactionID = retVal.TransactionID;
            EDIGWMessageID = retVal.EDIGWMessageID;
            EDIGWMessage = retVal.EDIGWMessage;
            return retVal.ErrorCode;
        }
    }
}
