//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSGlobal.VoiceRecorder.srSecurity {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com.dcsglobal.security", ConfigurationName="srSecurity.SecuritySoap")]
    public interface SecuritySoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://com.dcsglobal.security is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.security/Login", ReplyAction="*")]
        DCSGlobal.VoiceRecorder.srSecurity.LoginResponse Login(DCSGlobal.VoiceRecorder.srSecurity.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://com.dcsglobal.security", Order=0)]
        public DCSGlobal.VoiceRecorder.srSecurity.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(DCSGlobal.VoiceRecorder.srSecurity.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.security")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwd;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string UserName, string passwd) {
            this.UserName = UserName;
            this.passwd = passwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://com.dcsglobal.security", Order=0)]
        public DCSGlobal.VoiceRecorder.srSecurity.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(DCSGlobal.VoiceRecorder.srSecurity.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.security")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(int LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecuritySoapChannel : DCSGlobal.VoiceRecorder.srSecurity.SecuritySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecuritySoapClient : System.ServiceModel.ClientBase<DCSGlobal.VoiceRecorder.srSecurity.SecuritySoap>, DCSGlobal.VoiceRecorder.srSecurity.SecuritySoap {
        
        public SecuritySoapClient() {
        }
        
        public SecuritySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecuritySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuritySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuritySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.VoiceRecorder.srSecurity.LoginResponse DCSGlobal.VoiceRecorder.srSecurity.SecuritySoap.Login(DCSGlobal.VoiceRecorder.srSecurity.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public int Login(string UserName, string passwd) {
            DCSGlobal.VoiceRecorder.srSecurity.LoginRequest inValue = new DCSGlobal.VoiceRecorder.srSecurity.LoginRequest();
            inValue.Body = new DCSGlobal.VoiceRecorder.srSecurity.LoginRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.passwd = passwd;
            DCSGlobal.VoiceRecorder.srSecurity.LoginResponse retVal = ((DCSGlobal.VoiceRecorder.srSecurity.SecuritySoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
    }
}
