//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manual_test_app.sr {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="sr.ISampleService")]
    public interface ISampleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/TestFunction", ReplyAction="http://tempuri.org/ISampleService/TestFunctionResponse")]
        int TestFunction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/GetRealMessages", ReplyAction="http://tempuri.org/ISampleService/GetRealMessagesResponse")]
        string GetRealMessages(string OperatorID, string HospCode, string UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/Login", ReplyAction="http://tempuri.org/ISampleService/LoginResponse")]
        int Login(string USER_ID, string HospCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/KillList", ReplyAction="http://tempuri.org/ISampleService/KillListResponse")]
        int KillList(string TheString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISampleServiceChannel : Manual_test_app.sr.ISampleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleServiceClient : System.ServiceModel.ClientBase<Manual_test_app.sr.ISampleService>, Manual_test_app.sr.ISampleService {
        
        public SampleServiceClient() {
        }
        
        public SampleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int TestFunction() {
            return base.Channel.TestFunction();
        }
        
        public string GetRealMessages(string OperatorID, string HospCode, string UserId) {
            return base.Channel.GetRealMessages(OperatorID, HospCode, UserId);
        }
        
        public int Login(string USER_ID, string HospCode) {
            return base.Channel.Login(USER_ID, HospCode);
        }
        
        public int KillList(string TheString) {
            return base.Channel.KillList(TheString);
        }
    }
}
