//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSGlobal.VoiceRecorder.srVoiceRecorder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com.dcsglobal.voicerecorder", ConfigurationName="srVoiceRecorder.VoiceRecorderSoap")]
    public interface VoiceRecorderSoap {
        
        // CODEGEN: Generating message contract since element name TRACK_FILE_NAME from namespace http://com.dcsglobal.voicerecorder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/AddTrack", ReplyAction="*")]
        DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackResponse AddTrack(DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/TrackSent", ReplyAction="*")]
        int TrackSent(int TRACK_ID, int TRACK_SENT);
        
        // CODEGEN: Generating message contract since element name TRACK_DETAIL_SUBJECT from namespace http://com.dcsglobal.voicerecorder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/UpdateTrackDetails", ReplyAction="*")]
        DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackDetailsResponse UpdateTrackDetails(DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetHospCodeResult from namespace http://com.dcsglobal.voicerecorder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/GetHospCode", ReplyAction="*")]
        DCSGlobal.VoiceRecorder.srVoiceRecorder.GetHospCodeResponse GetHospCode(DCSGlobal.VoiceRecorder.srVoiceRecorder.GetHospCodeRequest request);
        
        // CODEGEN: Generating message contract since element name TRACK_DETAIL_SUBJECT from namespace http://com.dcsglobal.voicerecorder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/AddTrackDetails", ReplyAction="*")]
        DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackDetailsResponse AddTrackDetails(DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name TRACK_FILE_NAME from namespace http://com.dcsglobal.voicerecorder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/UpdateTrack", ReplyAction="*")]
        DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackResponse UpdateTrack(DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrack", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackRequestBody Body;
        
        public AddTrackRequest() {
        }
        
        public AddTrackRequest(DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class AddTrackRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRACK_FILE_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TRACK_SUBJECT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TRACK_NOTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TRACK_CONTACT_NUMBER;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TRACK_CONTACT_PERSON_FIRST;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TRACK_CONTACT_PERSON_LAST;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TRACK_CONTACT_PERSON_EMAIL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string USER_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TRACK_START_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TRACK_END_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ACCOUNT_NUMBER;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string MRN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DOR;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string SOURCE_DEVICE;
        
        public AddTrackRequestBody() {
        }
        
        public AddTrackRequestBody(string TRACK_FILE_NAME, string TRACK_SUBJECT, string TRACK_NOTE, string TRACK_CONTACT_NUMBER, string TRACK_CONTACT_PERSON_FIRST, string TRACK_CONTACT_PERSON_LAST, string TRACK_CONTACT_PERSON_EMAIL, string USER_ID, string TRACK_START_TIME, string TRACK_END_TIME, string ACCOUNT_NUMBER, string MRN, string DOR, string SOURCE_DEVICE) {
            this.TRACK_FILE_NAME = TRACK_FILE_NAME;
            this.TRACK_SUBJECT = TRACK_SUBJECT;
            this.TRACK_NOTE = TRACK_NOTE;
            this.TRACK_CONTACT_NUMBER = TRACK_CONTACT_NUMBER;
            this.TRACK_CONTACT_PERSON_FIRST = TRACK_CONTACT_PERSON_FIRST;
            this.TRACK_CONTACT_PERSON_LAST = TRACK_CONTACT_PERSON_LAST;
            this.TRACK_CONTACT_PERSON_EMAIL = TRACK_CONTACT_PERSON_EMAIL;
            this.USER_ID = USER_ID;
            this.TRACK_START_TIME = TRACK_START_TIME;
            this.TRACK_END_TIME = TRACK_END_TIME;
            this.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            this.MRN = MRN;
            this.DOR = DOR;
            this.SOURCE_DEVICE = SOURCE_DEVICE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrackResponse", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackResponseBody Body;
        
        public AddTrackResponse() {
        }
        
        public AddTrackResponse(DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class AddTrackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddTrackResult;
        
        public AddTrackResponseBody() {
        }
        
        public AddTrackResponseBody(int AddTrackResult) {
            this.AddTrackResult = AddTrackResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTrackDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTrackDetails", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackDetailsRequestBody Body;
        
        public UpdateTrackDetailsRequest() {
        }
        
        public UpdateTrackDetailsRequest(DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class UpdateTrackDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TRACK_DETAIL_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TRACK_DETAIL_SUBJECT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TRACK_DETAIL_NOTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string USER_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int START_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int END_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ACCOUNT_NUMBER;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string MRN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DOR;
        
        public UpdateTrackDetailsRequestBody() {
        }
        
        public UpdateTrackDetailsRequestBody(int TRACK_DETAIL_ID, string TRACK_DETAIL_SUBJECT, string TRACK_DETAIL_NOTE, string USER_ID, int START_TIME, int END_TIME, string ACCOUNT_NUMBER, string MRN, string DOR) {
            this.TRACK_DETAIL_ID = TRACK_DETAIL_ID;
            this.TRACK_DETAIL_SUBJECT = TRACK_DETAIL_SUBJECT;
            this.TRACK_DETAIL_NOTE = TRACK_DETAIL_NOTE;
            this.USER_ID = USER_ID;
            this.START_TIME = START_TIME;
            this.END_TIME = END_TIME;
            this.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            this.MRN = MRN;
            this.DOR = DOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTrackDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTrackDetailsResponse", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackDetailsResponseBody Body;
        
        public UpdateTrackDetailsResponse() {
        }
        
        public UpdateTrackDetailsResponse(DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class UpdateTrackDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateTrackDetailsResult;
        
        public UpdateTrackDetailsResponseBody() {
        }
        
        public UpdateTrackDetailsResponseBody(int UpdateTrackDetailsResult) {
            this.UpdateTrackDetailsResult = UpdateTrackDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHospCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHospCode", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.VoiceRecorder.srVoiceRecorder.GetHospCodeRequestBody Body;
        
        public GetHospCodeRequest() {
        }
        
        public GetHospCodeRequest(DCSGlobal.VoiceRecorder.srVoiceRecorder.GetHospCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetHospCodeRequestBody {
        
        public GetHospCodeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHospCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHospCodeResponse", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.VoiceRecorder.srVoiceRecorder.GetHospCodeResponseBody Body;
        
        public GetHospCodeResponse() {
        }
        
        public GetHospCodeResponse(DCSGlobal.VoiceRecorder.srVoiceRecorder.GetHospCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class GetHospCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHospCodeResult;
        
        public GetHospCodeResponseBody() {
        }
        
        public GetHospCodeResponseBody(string GetHospCodeResult) {
            this.GetHospCodeResult = GetHospCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrackDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrackDetails", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackDetailsRequestBody Body;
        
        public AddTrackDetailsRequest() {
        }
        
        public AddTrackDetailsRequest(DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class AddTrackDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TRACK_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TRACK_DETAIL_SUBJECT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TRACK_DETAIL_NOTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string USER_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int START_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int END_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ACCOUNT_NUMBER;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string MRN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DOR;
        
        public AddTrackDetailsRequestBody() {
        }
        
        public AddTrackDetailsRequestBody(int TRACK_ID, string TRACK_DETAIL_SUBJECT, string TRACK_DETAIL_NOTE, string USER_ID, int START_TIME, int END_TIME, string ACCOUNT_NUMBER, string MRN, string DOR) {
            this.TRACK_ID = TRACK_ID;
            this.TRACK_DETAIL_SUBJECT = TRACK_DETAIL_SUBJECT;
            this.TRACK_DETAIL_NOTE = TRACK_DETAIL_NOTE;
            this.USER_ID = USER_ID;
            this.START_TIME = START_TIME;
            this.END_TIME = END_TIME;
            this.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            this.MRN = MRN;
            this.DOR = DOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrackDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrackDetailsResponse", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackDetailsResponseBody Body;
        
        public AddTrackDetailsResponse() {
        }
        
        public AddTrackDetailsResponse(DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class AddTrackDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddTrackDetailsResult;
        
        public AddTrackDetailsResponseBody() {
        }
        
        public AddTrackDetailsResponseBody(int AddTrackDetailsResult) {
            this.AddTrackDetailsResult = AddTrackDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTrackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTrack", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackRequestBody Body;
        
        public UpdateTrackRequest() {
        }
        
        public UpdateTrackRequest(DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class UpdateTrackRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TrackID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TRACK_FILE_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TRACK_SUBJECT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TRACK_NOTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TRACK_CONTACT_NUMBER;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TRACK_CONTACT_PERSON_FIRST;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TRACK_CONTACT_PERSON_LAST;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TRACK_CONTACT_PERSON_EMAIL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string USER_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TRACK_START_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string TRACK_END_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ACCOUNT_NUMBER;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string MRN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DOR;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string SOURCE_DEVICE;
        
        public UpdateTrackRequestBody() {
        }
        
        public UpdateTrackRequestBody(int TrackID, string TRACK_FILE_NAME, string TRACK_SUBJECT, string TRACK_NOTE, string TRACK_CONTACT_NUMBER, string TRACK_CONTACT_PERSON_FIRST, string TRACK_CONTACT_PERSON_LAST, string TRACK_CONTACT_PERSON_EMAIL, string USER_ID, string TRACK_START_TIME, string TRACK_END_TIME, string ACCOUNT_NUMBER, string MRN, string DOR, string SOURCE_DEVICE) {
            this.TrackID = TrackID;
            this.TRACK_FILE_NAME = TRACK_FILE_NAME;
            this.TRACK_SUBJECT = TRACK_SUBJECT;
            this.TRACK_NOTE = TRACK_NOTE;
            this.TRACK_CONTACT_NUMBER = TRACK_CONTACT_NUMBER;
            this.TRACK_CONTACT_PERSON_FIRST = TRACK_CONTACT_PERSON_FIRST;
            this.TRACK_CONTACT_PERSON_LAST = TRACK_CONTACT_PERSON_LAST;
            this.TRACK_CONTACT_PERSON_EMAIL = TRACK_CONTACT_PERSON_EMAIL;
            this.USER_ID = USER_ID;
            this.TRACK_START_TIME = TRACK_START_TIME;
            this.TRACK_END_TIME = TRACK_END_TIME;
            this.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            this.MRN = MRN;
            this.DOR = DOR;
            this.SOURCE_DEVICE = SOURCE_DEVICE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTrackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTrackResponse", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackResponseBody Body;
        
        public UpdateTrackResponse() {
        }
        
        public UpdateTrackResponse(DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class UpdateTrackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateTrackResult;
        
        public UpdateTrackResponseBody() {
        }
        
        public UpdateTrackResponseBody(int UpdateTrackResult) {
            this.UpdateTrackResult = UpdateTrackResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VoiceRecorderSoapChannel : DCSGlobal.VoiceRecorder.srVoiceRecorder.VoiceRecorderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoiceRecorderSoapClient : System.ServiceModel.ClientBase<DCSGlobal.VoiceRecorder.srVoiceRecorder.VoiceRecorderSoap>, DCSGlobal.VoiceRecorder.srVoiceRecorder.VoiceRecorderSoap {
        
        public VoiceRecorderSoapClient() {
        }
        
        public VoiceRecorderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoiceRecorderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceRecorderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceRecorderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackResponse DCSGlobal.VoiceRecorder.srVoiceRecorder.VoiceRecorderSoap.AddTrack(DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackRequest request) {
            return base.Channel.AddTrack(request);
        }
        
        public int AddTrack(string TRACK_FILE_NAME, string TRACK_SUBJECT, string TRACK_NOTE, string TRACK_CONTACT_NUMBER, string TRACK_CONTACT_PERSON_FIRST, string TRACK_CONTACT_PERSON_LAST, string TRACK_CONTACT_PERSON_EMAIL, string USER_ID, string TRACK_START_TIME, string TRACK_END_TIME, string ACCOUNT_NUMBER, string MRN, string DOR, string SOURCE_DEVICE) {
            DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackRequest inValue = new DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackRequest();
            inValue.Body = new DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackRequestBody();
            inValue.Body.TRACK_FILE_NAME = TRACK_FILE_NAME;
            inValue.Body.TRACK_SUBJECT = TRACK_SUBJECT;
            inValue.Body.TRACK_NOTE = TRACK_NOTE;
            inValue.Body.TRACK_CONTACT_NUMBER = TRACK_CONTACT_NUMBER;
            inValue.Body.TRACK_CONTACT_PERSON_FIRST = TRACK_CONTACT_PERSON_FIRST;
            inValue.Body.TRACK_CONTACT_PERSON_LAST = TRACK_CONTACT_PERSON_LAST;
            inValue.Body.TRACK_CONTACT_PERSON_EMAIL = TRACK_CONTACT_PERSON_EMAIL;
            inValue.Body.USER_ID = USER_ID;
            inValue.Body.TRACK_START_TIME = TRACK_START_TIME;
            inValue.Body.TRACK_END_TIME = TRACK_END_TIME;
            inValue.Body.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            inValue.Body.MRN = MRN;
            inValue.Body.DOR = DOR;
            inValue.Body.SOURCE_DEVICE = SOURCE_DEVICE;
            DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackResponse retVal = ((DCSGlobal.VoiceRecorder.srVoiceRecorder.VoiceRecorderSoap)(this)).AddTrack(inValue);
            return retVal.Body.AddTrackResult;
        }
        
        public int TrackSent(int TRACK_ID, int TRACK_SENT) {
            return base.Channel.TrackSent(TRACK_ID, TRACK_SENT);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackDetailsResponse DCSGlobal.VoiceRecorder.srVoiceRecorder.VoiceRecorderSoap.UpdateTrackDetails(DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackDetailsRequest request) {
            return base.Channel.UpdateTrackDetails(request);
        }
        
        public int UpdateTrackDetails(int TRACK_DETAIL_ID, string TRACK_DETAIL_SUBJECT, string TRACK_DETAIL_NOTE, string USER_ID, int START_TIME, int END_TIME, string ACCOUNT_NUMBER, string MRN, string DOR) {
            DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackDetailsRequest inValue = new DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackDetailsRequest();
            inValue.Body = new DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackDetailsRequestBody();
            inValue.Body.TRACK_DETAIL_ID = TRACK_DETAIL_ID;
            inValue.Body.TRACK_DETAIL_SUBJECT = TRACK_DETAIL_SUBJECT;
            inValue.Body.TRACK_DETAIL_NOTE = TRACK_DETAIL_NOTE;
            inValue.Body.USER_ID = USER_ID;
            inValue.Body.START_TIME = START_TIME;
            inValue.Body.END_TIME = END_TIME;
            inValue.Body.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            inValue.Body.MRN = MRN;
            inValue.Body.DOR = DOR;
            DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackDetailsResponse retVal = ((DCSGlobal.VoiceRecorder.srVoiceRecorder.VoiceRecorderSoap)(this)).UpdateTrackDetails(inValue);
            return retVal.Body.UpdateTrackDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.VoiceRecorder.srVoiceRecorder.GetHospCodeResponse DCSGlobal.VoiceRecorder.srVoiceRecorder.VoiceRecorderSoap.GetHospCode(DCSGlobal.VoiceRecorder.srVoiceRecorder.GetHospCodeRequest request) {
            return base.Channel.GetHospCode(request);
        }
        
        public string GetHospCode() {
            DCSGlobal.VoiceRecorder.srVoiceRecorder.GetHospCodeRequest inValue = new DCSGlobal.VoiceRecorder.srVoiceRecorder.GetHospCodeRequest();
            inValue.Body = new DCSGlobal.VoiceRecorder.srVoiceRecorder.GetHospCodeRequestBody();
            DCSGlobal.VoiceRecorder.srVoiceRecorder.GetHospCodeResponse retVal = ((DCSGlobal.VoiceRecorder.srVoiceRecorder.VoiceRecorderSoap)(this)).GetHospCode(inValue);
            return retVal.Body.GetHospCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackDetailsResponse DCSGlobal.VoiceRecorder.srVoiceRecorder.VoiceRecorderSoap.AddTrackDetails(DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackDetailsRequest request) {
            return base.Channel.AddTrackDetails(request);
        }
        
        public int AddTrackDetails(int TRACK_ID, string TRACK_DETAIL_SUBJECT, string TRACK_DETAIL_NOTE, string USER_ID, int START_TIME, int END_TIME, string ACCOUNT_NUMBER, string MRN, string DOR) {
            DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackDetailsRequest inValue = new DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackDetailsRequest();
            inValue.Body = new DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackDetailsRequestBody();
            inValue.Body.TRACK_ID = TRACK_ID;
            inValue.Body.TRACK_DETAIL_SUBJECT = TRACK_DETAIL_SUBJECT;
            inValue.Body.TRACK_DETAIL_NOTE = TRACK_DETAIL_NOTE;
            inValue.Body.USER_ID = USER_ID;
            inValue.Body.START_TIME = START_TIME;
            inValue.Body.END_TIME = END_TIME;
            inValue.Body.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            inValue.Body.MRN = MRN;
            inValue.Body.DOR = DOR;
            DCSGlobal.VoiceRecorder.srVoiceRecorder.AddTrackDetailsResponse retVal = ((DCSGlobal.VoiceRecorder.srVoiceRecorder.VoiceRecorderSoap)(this)).AddTrackDetails(inValue);
            return retVal.Body.AddTrackDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackResponse DCSGlobal.VoiceRecorder.srVoiceRecorder.VoiceRecorderSoap.UpdateTrack(DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackRequest request) {
            return base.Channel.UpdateTrack(request);
        }
        
        public int UpdateTrack(int TrackID, string TRACK_FILE_NAME, string TRACK_SUBJECT, string TRACK_NOTE, string TRACK_CONTACT_NUMBER, string TRACK_CONTACT_PERSON_FIRST, string TRACK_CONTACT_PERSON_LAST, string TRACK_CONTACT_PERSON_EMAIL, string USER_ID, string TRACK_START_TIME, string TRACK_END_TIME, string ACCOUNT_NUMBER, string MRN, string DOR, string SOURCE_DEVICE) {
            DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackRequest inValue = new DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackRequest();
            inValue.Body = new DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackRequestBody();
            inValue.Body.TrackID = TrackID;
            inValue.Body.TRACK_FILE_NAME = TRACK_FILE_NAME;
            inValue.Body.TRACK_SUBJECT = TRACK_SUBJECT;
            inValue.Body.TRACK_NOTE = TRACK_NOTE;
            inValue.Body.TRACK_CONTACT_NUMBER = TRACK_CONTACT_NUMBER;
            inValue.Body.TRACK_CONTACT_PERSON_FIRST = TRACK_CONTACT_PERSON_FIRST;
            inValue.Body.TRACK_CONTACT_PERSON_LAST = TRACK_CONTACT_PERSON_LAST;
            inValue.Body.TRACK_CONTACT_PERSON_EMAIL = TRACK_CONTACT_PERSON_EMAIL;
            inValue.Body.USER_ID = USER_ID;
            inValue.Body.TRACK_START_TIME = TRACK_START_TIME;
            inValue.Body.TRACK_END_TIME = TRACK_END_TIME;
            inValue.Body.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            inValue.Body.MRN = MRN;
            inValue.Body.DOR = DOR;
            inValue.Body.SOURCE_DEVICE = SOURCE_DEVICE;
            DCSGlobal.VoiceRecorder.srVoiceRecorder.UpdateTrackResponse retVal = ((DCSGlobal.VoiceRecorder.srVoiceRecorder.VoiceRecorderSoap)(this)).UpdateTrack(inValue);
            return retVal.Body.UpdateTrackResult;
        }
    }
}
