//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSGlobal.Recorder.srvVoiceRecorder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com.dcsglobal.voicerecorder", ConfigurationName="srvVoiceRecorder.VoiceRecorderSoap")]
    public interface VoiceRecorderSoap {
        
        // CODEGEN: Generating message contract since element name TRACK_FILE_NAME from namespace http://com.dcsglobal.voicerecorder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/AddTrack", ReplyAction="*")]
        DCSGlobal.Recorder.srvVoiceRecorder.AddTrackResponse AddTrack(DCSGlobal.Recorder.srvVoiceRecorder.AddTrackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/TrackSent", ReplyAction="*")]
        int TrackSent(int TRACK_ID, int TRACK_SENT);
        
        // CODEGEN: Generating message contract since element name TRACK_DETAIL_NOTE from namespace http://com.dcsglobal.voicerecorder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.dcsglobal.voicerecorder/AddTrackDetails", ReplyAction="*")]
        DCSGlobal.Recorder.srvVoiceRecorder.AddTrackDetailsResponse AddTrackDetails(DCSGlobal.Recorder.srvVoiceRecorder.AddTrackDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrack", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Recorder.srvVoiceRecorder.AddTrackRequestBody Body;
        
        public AddTrackRequest() {
        }
        
        public AddTrackRequest(DCSGlobal.Recorder.srvVoiceRecorder.AddTrackRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class AddTrackRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRACK_FILE_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TRACK_SUBJECT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TRACK_NOTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TRACK_CONTACT_NUMBER;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TRACK_CONTACT_PERSON_FIRST;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TRACK_CONTACT_PERSON_LAST;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TRACK_CONTACT_PERSON_EMAIL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string USER_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TRACK_START_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TRACK_END_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ACCOUNT_NUMBER;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string MRN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DOR;
        
        public AddTrackRequestBody() {
        }
        
        public AddTrackRequestBody(string TRACK_FILE_NAME, string TRACK_SUBJECT, string TRACK_NOTE, string TRACK_CONTACT_NUMBER, string TRACK_CONTACT_PERSON_FIRST, string TRACK_CONTACT_PERSON_LAST, string TRACK_CONTACT_PERSON_EMAIL, string USER_ID, string TRACK_START_TIME, string TRACK_END_TIME, string ACCOUNT_NUMBER, string MRN, string DOR) {
            this.TRACK_FILE_NAME = TRACK_FILE_NAME;
            this.TRACK_SUBJECT = TRACK_SUBJECT;
            this.TRACK_NOTE = TRACK_NOTE;
            this.TRACK_CONTACT_NUMBER = TRACK_CONTACT_NUMBER;
            this.TRACK_CONTACT_PERSON_FIRST = TRACK_CONTACT_PERSON_FIRST;
            this.TRACK_CONTACT_PERSON_LAST = TRACK_CONTACT_PERSON_LAST;
            this.TRACK_CONTACT_PERSON_EMAIL = TRACK_CONTACT_PERSON_EMAIL;
            this.USER_ID = USER_ID;
            this.TRACK_START_TIME = TRACK_START_TIME;
            this.TRACK_END_TIME = TRACK_END_TIME;
            this.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            this.MRN = MRN;
            this.DOR = DOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrackResponse", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Recorder.srvVoiceRecorder.AddTrackResponseBody Body;
        
        public AddTrackResponse() {
        }
        
        public AddTrackResponse(DCSGlobal.Recorder.srvVoiceRecorder.AddTrackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class AddTrackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddTrackResult;
        
        public AddTrackResponseBody() {
        }
        
        public AddTrackResponseBody(int AddTrackResult) {
            this.AddTrackResult = AddTrackResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrackDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrackDetails", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Recorder.srvVoiceRecorder.AddTrackDetailsRequestBody Body;
        
        public AddTrackDetailsRequest() {
        }
        
        public AddTrackDetailsRequest(DCSGlobal.Recorder.srvVoiceRecorder.AddTrackDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class AddTrackDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TRACK_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TRACK_DETAIL_NOTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string USER_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int START_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int END_TIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ACCOUNT_NUMBER;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MRN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string DOR;
        
        public AddTrackDetailsRequestBody() {
        }
        
        public AddTrackDetailsRequestBody(int TRACK_ID, string TRACK_DETAIL_NOTE, string USER_ID, int START_TIME, int END_TIME, string ACCOUNT_NUMBER, string MRN, string DOR) {
            this.TRACK_ID = TRACK_ID;
            this.TRACK_DETAIL_NOTE = TRACK_DETAIL_NOTE;
            this.USER_ID = USER_ID;
            this.START_TIME = START_TIME;
            this.END_TIME = END_TIME;
            this.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            this.MRN = MRN;
            this.DOR = DOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrackDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrackDetailsResponse", Namespace="http://com.dcsglobal.voicerecorder", Order=0)]
        public DCSGlobal.Recorder.srvVoiceRecorder.AddTrackDetailsResponseBody Body;
        
        public AddTrackDetailsResponse() {
        }
        
        public AddTrackDetailsResponse(DCSGlobal.Recorder.srvVoiceRecorder.AddTrackDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.dcsglobal.voicerecorder")]
    public partial class AddTrackDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddTrackDetailsResult;
        
        public AddTrackDetailsResponseBody() {
        }
        
        public AddTrackDetailsResponseBody(int AddTrackDetailsResult) {
            this.AddTrackDetailsResult = AddTrackDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VoiceRecorderSoapChannel : DCSGlobal.Recorder.srvVoiceRecorder.VoiceRecorderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoiceRecorderSoapClient : System.ServiceModel.ClientBase<DCSGlobal.Recorder.srvVoiceRecorder.VoiceRecorderSoap>, DCSGlobal.Recorder.srvVoiceRecorder.VoiceRecorderSoap {
        
        public VoiceRecorderSoapClient() {
        }
        
        public VoiceRecorderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoiceRecorderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceRecorderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceRecorderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.Recorder.srvVoiceRecorder.AddTrackResponse DCSGlobal.Recorder.srvVoiceRecorder.VoiceRecorderSoap.AddTrack(DCSGlobal.Recorder.srvVoiceRecorder.AddTrackRequest request) {
            return base.Channel.AddTrack(request);
        }
        
        public int AddTrack(string TRACK_FILE_NAME, string TRACK_SUBJECT, string TRACK_NOTE, string TRACK_CONTACT_NUMBER, string TRACK_CONTACT_PERSON_FIRST, string TRACK_CONTACT_PERSON_LAST, string TRACK_CONTACT_PERSON_EMAIL, string USER_ID, string TRACK_START_TIME, string TRACK_END_TIME, string ACCOUNT_NUMBER, string MRN, string DOR) {
            DCSGlobal.Recorder.srvVoiceRecorder.AddTrackRequest inValue = new DCSGlobal.Recorder.srvVoiceRecorder.AddTrackRequest();
            inValue.Body = new DCSGlobal.Recorder.srvVoiceRecorder.AddTrackRequestBody();
            inValue.Body.TRACK_FILE_NAME = TRACK_FILE_NAME;
            inValue.Body.TRACK_SUBJECT = TRACK_SUBJECT;
            inValue.Body.TRACK_NOTE = TRACK_NOTE;
            inValue.Body.TRACK_CONTACT_NUMBER = TRACK_CONTACT_NUMBER;
            inValue.Body.TRACK_CONTACT_PERSON_FIRST = TRACK_CONTACT_PERSON_FIRST;
            inValue.Body.TRACK_CONTACT_PERSON_LAST = TRACK_CONTACT_PERSON_LAST;
            inValue.Body.TRACK_CONTACT_PERSON_EMAIL = TRACK_CONTACT_PERSON_EMAIL;
            inValue.Body.USER_ID = USER_ID;
            inValue.Body.TRACK_START_TIME = TRACK_START_TIME;
            inValue.Body.TRACK_END_TIME = TRACK_END_TIME;
            inValue.Body.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            inValue.Body.MRN = MRN;
            inValue.Body.DOR = DOR;
            DCSGlobal.Recorder.srvVoiceRecorder.AddTrackResponse retVal = ((DCSGlobal.Recorder.srvVoiceRecorder.VoiceRecorderSoap)(this)).AddTrack(inValue);
            return retVal.Body.AddTrackResult;
        }
        
        public int TrackSent(int TRACK_ID, int TRACK_SENT) {
            return base.Channel.TrackSent(TRACK_ID, TRACK_SENT);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DCSGlobal.Recorder.srvVoiceRecorder.AddTrackDetailsResponse DCSGlobal.Recorder.srvVoiceRecorder.VoiceRecorderSoap.AddTrackDetails(DCSGlobal.Recorder.srvVoiceRecorder.AddTrackDetailsRequest request) {
            return base.Channel.AddTrackDetails(request);
        }
        
        public int AddTrackDetails(int TRACK_ID, string TRACK_DETAIL_NOTE, string USER_ID, int START_TIME, int END_TIME, string ACCOUNT_NUMBER, string MRN, string DOR) {
            DCSGlobal.Recorder.srvVoiceRecorder.AddTrackDetailsRequest inValue = new DCSGlobal.Recorder.srvVoiceRecorder.AddTrackDetailsRequest();
            inValue.Body = new DCSGlobal.Recorder.srvVoiceRecorder.AddTrackDetailsRequestBody();
            inValue.Body.TRACK_ID = TRACK_ID;
            inValue.Body.TRACK_DETAIL_NOTE = TRACK_DETAIL_NOTE;
            inValue.Body.USER_ID = USER_ID;
            inValue.Body.START_TIME = START_TIME;
            inValue.Body.END_TIME = END_TIME;
            inValue.Body.ACCOUNT_NUMBER = ACCOUNT_NUMBER;
            inValue.Body.MRN = MRN;
            inValue.Body.DOR = DOR;
            DCSGlobal.Recorder.srvVoiceRecorder.AddTrackDetailsResponse retVal = ((DCSGlobal.Recorder.srvVoiceRecorder.VoiceRecorderSoap)(this)).AddTrackDetails(inValue);
            return retVal.Body.AddTrackDetailsResult;
        }
    }
}
